# Generated by Django 4.2.16 on 2024-11-17 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartmodel_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='coupon',
        ),
    ]
