# Generated by Django 4.2.16 on 2024-10-17 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'ordering': ['-created_date'], 'verbose_name': 'تماس', 'verbose_name_plural': 'تماس ها'},
        ),
    ]
