# Generated by Django 4.2.16 on 2024-10-17 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_contactmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'ordering': ['-created_date']},
        ),
    ]
