# Generated by Django 4.2.16 on 2024-11-12 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_failed_login_attempts_user_last_failed_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FailedLoginAttempt',
        ),
    ]
