# Generated by Django 4.2.16 on 2024-11-13 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_is_active_activationtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivationToken',
        ),
    ]
