# Generated by Django 4.2.16 on 2024-11-17 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='state',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.useraddressmodel'),
        ),
    ]
