# Generated by Django 4.2.16 on 2024-11-29 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmodel',
            old_name='ref_id',
            new_name='paymentnumber',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='authority_id',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='response_code',
        ),
    ]
